### ISSUE TITLE
[FEAT]: Reduce redundancy

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/py-series#1]
# Feature Request

## Is your feature request related to a problem? Please describe:

Some redundant functions are present in the Series.py file.

## Describe the solution you'd like

https://github.com/Vyvy-vi/py-series/blob/c8c106eb83db06def75e45f211b97e873d165332/Series.py#L65-L108
The functions should be generalised to a new function `nth_power_sum_check` that takes an argument for parameter n

**Comment by laisvigas** [comment]
Hey, I'm interested in working on this issue. Is it possible for me to contribute to it?

**Comment by Vyvy-vi** [comment]
Sure, @laisvigas!

**Comment by laisvigas** [comment]
Hi @Vyvy-vi, 

Thank you for assigning me to this task. This is actually my first time contributing to a repository, so I want to make sure I'm doing everything correctly. I've encountered an issue with permissions as I try to push changes. Below is a screenshot of the error message I received:

![Screenshot Erro [403]](https://github.com/Vyvy-vi/py-series/assets/119849251/f63f8515-86e9-4594-bd25-7b2e76215424)

As you can see, it seems I don't have the necessary permissions to push to the repository. Could you please guide me on how to proceed or grant me the write permissions needed for this branch?

Your assistance and guidance would be greatly appreciated.

**Comment by Vyvy-vi** [comment]
Hi @laisvigas, thanks for showing interest in contributing!

It looks like you're trying to push code to my repository, but you don't have permission to push on here.
The issue can be resolved by creating a _fork_ of this repository and setting that as the origin on your local git repository and then opening a Pull Request from your fork to this repository.

That's a lot, but here's the info unpacked -
- Open https://github.com/Vyvy-vi/py-series/ and click on the "Fork" button second from top right
- Copy URL of your forked repo (It should look like https://github.com/laisvigas/py-series)
- Open your terminal and run `git remote set-url origin FORK_URL_COPIED_ABOVE`
- Run `git push -u origin feature/reduce-redundancy`
- Open https://github.com/laisvigas/py-series and click the Pull Request Button

Feel free to ask for help.

**Comment by laisvigas** [comment]
Hello @Vyvy-vi,

Thank you for your patience and guidance! I've followed your instructions and successfully pushed my changes to my fork. I've now opened a pull request for your review. Please feel free to take a look at your earliest convenience. If you have any feedback or questions, don't hesitate to let me know.

Thanks again for your help and patience!
